# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Build

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:


      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: clean build with maven - no tests
        run: mvn clean compile

      - name: build docker image using maven
        run: mvn install -DskipTests

      - name: ensure fresh docker login by logging out
        run: docker logout
      
      - name: log back in now
        run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: now push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/listshop-server:${GITHUB_REF##*/}
        


